plugins {
    alias(libs.plugins.fabric.loom)
    alias(libs.plugins.maven.publish)
    alias(libs.plugins.gradle.build.tools)
}

Properties props = buildUtils.loadProperties('publish.properties')  // will be empty, if the file is missing

version = "${project.mod_version}+${libs.versions.minecraft.get()}"
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

int javaVersion = Integer.parseInt(libs.versions.java.get())

repositories {
    maven {
        url "https://repo.lclpnet.work/repository/internal"
    }
}

loom {
    splitEnvironmentSourceSets()

    mods {
        "modid" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

fabricApi {
    configureDataGeneration()
}

dependencies {
    minecraft(libs.minecraft)

    mappings loom.officialMojangMappings()

    modImplementation(libs.fabric.loader)
    modImplementation(libs.fabric.api)

    testImplementation(libs.fabric.loader.junit)
}

test {
    useJUnitPlatform()
}

processResources {
	inputs.property "version", project.version
    inputs.property "loader_version", libs.versions.fabric.loader.get()
    inputs.property "minecraft_compat", project.minecraft_compat
    inputs.property "java_version", libs.versions.java.get()

	filesMatching("fabric.mod.json") {
		expand "version": project.version,
                "loader_version": libs.versions.fabric.loader.get(),
                "minecraft_compat": project.minecraft_compat,
                "java_version": libs.versions.java.get()
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release.set(javaVersion)
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.toVersion(javaVersion)
    targetCompatibility = JavaVersion.toVersion(javaVersion)
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}"}
	}
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = project.base.archivesName.get()

            from components.java

            pom {
                name = 'Test Mod'
                description = 'This is an example description! Tell everyone what your mod is about!'
            }
        }
    }

    // automatically use DEPLOY_URL, DEPLOY_USER and DEPLOY_PASSWORD environment variables
    // or mavenHost, mavenUser and mavenPassword from props
    buildUtils.setupPublishRepository(repositories, props)
}